### ISSUE TITLE
Paste Text Ignores Branch "Directories" (e.g. Feature Branches)

### ISSUE THREAD

**Issue by conatus** [DTrejo/rotten#10]
If you are creating a branch called `feature/thing` then the command will be returned as simply `thing`, stripping the branch psuedo-directory.

```
git push origin :thing; git branch -D thing;
```

Thanks for the awesome code!

**Comment by DTrejo** [comment]
I _think_ this will be fixed by #9 once I merge it?

To create a "directory" I just do `git push origin :feature/thing`?

**Comment by inkel** [comment]
@DTrejo yes, this should be fixed once #9 is merged.

**Comment by conatus** [comment]
Great to see someone has had the same problem. Would be sweet to get this in the code!

**Comment by DTrejo** [comment]
should be fixed!
Thanks!

**Comment by conatus** [comment]
:joy_cat:
